In [1]:
import pandas as pd

df = pd.read_csv('Crawling_KPK_Tweet.csv', encoding='ISO-8859-1')
df.head()

,IdTweet,IdUser,UserName,ScreenName,Location,TweetAt,UploadTweet,OriginalTweet
0,1471330854412558337,1407659965515370496,Shodiq Anwar,ShodiqAnwar5,"Kota Surabaya, Jawa Timur",2021-12-16 04:06:26+00:00,Twitter for Android,RT @temponewsroom: Sebanyak 44 eks pegawai KPK...
1,1471330825526394881,1173626760,Nah_Sittoae,Chirp_NAH_Sitto,Indonesian,2021-12-16 04:06:19+00:00,Twitter for Android,"@ed_tirta @KPK_RI @jokowi Harus diakui bahwa ""..."
2,1471330815380373504,1346814043818917889,jebeng tetuko,SenoWerkudoro4,NaN,2021-12-16 04:06:17+00:00,Twitter for Android,@FerdinandHaean3 @KPK_RI Akibat kebodohan .dar...
3,1471330791493750790,589904790,ÃetaAvengers,justpeys,NaN,2021-12-16 04:06:11+00:00,Twitter for Android,@FerdinandHaean3 @KPK_RI ini saya setuju sekal...
4,1471330783285571587,1451753998046810112,@2komaini_ahmad4,2komaini_ahmad4,NaN,2021-12-16 04:06:09+00:00,Twitter Web App,RT @Dandhy_Laksono: Dari yang tersisa seperti ...